### ISSUE TITLE
freetype crashes

### ISSUE THREAD

**Issue by SvenWollinger** [xpenatan/gdx-teavm#100]
Hello,
from what i can tell im not missing anything from the example, outside of the fact that im using kotlin.
Im getting this error message in my browser when FreeType is initialized:
![](https://media.discordapp.net/attachments/1049561238369210438/1115252918426288211/image.png?width=1553&height=322)
Ive used gdx-liftoff to generate my project and the teavm module has the neccessary extension to work with freetype.
Im using my generator like this:
```        
val params = FreeTypeFontGenerator.FreeTypeFontParameter().apply {
    this.size = size
    borderColor = com.badlogic.gdx.graphics.Color.BLACK
    borderWidth = 2F
}

val font: BitmapFont
FreeTypeFontGenerator(Gdx.files.internal("font.ttf")).apply {
    font = generateFont(params)
    dispose()
}
```
But i doubt that that is the issue, as it crashes even without the generator, when im manually calling FreeType.initFreeType();
Id be very thankfull if you could point me in the right direction here :)

**Comment by dragbone** [comment]
Hey @SvenWollinger, if you still have the same problem try updating to the latest version, that has fixed it for me (b4 -> b6)
