### ISSUE TITLE
You cannot have any subfolder called assets in your assets folder hierarchy.

### ISSUE THREAD

**Issue by antzGames** [xpenatan/gdx-teavm#102]
So I worked on getting Mundus runtime for libGDX (https://github.com/JamesTKhan/Mundus) working on TeaVM.

Mundus projects have an ```assets``` directory in the root of its project folder.

TeaVM did not like this and it changed the actual path to the Mundus resource in the directory.  I think teaVM replaces all instances ```assets``` in the each file path.  

Here is an example below.  The correct path should be ```mundus2/assets/xxxx``` but it looks like it puts it in the front.

![image](https://github.com/xpenatan/gdx-teavm/assets/10563814/b2945b5e-e2cc-4c43-aa73-18a721cb9cee)

I made some changes to Mundus so that you can set the asset folder to be any name and it works fine now.

This is more as a heads up.

**Comment by xpenatan** [comment]
Hey, this bug still happening ?

the idea is to move all assets to be inside assets folder.  So I guess it should be "assets/mundus2/assets/xxxx".

Maybe the regex is messing up with file that contains assets string. https://github.com/xpenatan/gdx-teavm/blob/master/backends/backend-teavm/src/main/java/com/github/xpenatan/gdx/backends/teavm/config/AssetsCopy.java#L122.

**Comment by antzGames** [comment]
Answer: Do not know.

So in my fork of Mundus, I can rename the asset folder.  This removes the issue.  But yes I also suspect the regex logic is messing up.

Maybe on your side, you can rename TEAVM's asset folder to `teavm_assets` so that it doesn't cause issues for any other library?

**Comment by antzGames** [comment]
Ok it looks like you fixed it.  Going to close the issue.
