### ISSUE TITLE
Update libGDX to 1.12.0?

### ISSUE THREAD

**Issue by noblemaster** [xpenatan/gdx-teavm#104]
Now that libGDX 1.12.0 is out, would be nice to have a new release here also? 😄 

- libGDX 1.12.0: https://libgdx.com/news/2023/07/gdx-1-12

https://github.com/xpenatan/gdx-teavm/blob/a55a376b9b95d7f139d6f4af38df0e11c51a062b/dependencies.gradle#L19

**Comment by xpenatan** [comment]
Done =)
