### ISSUE TITLE
Audio question on mobile browsers

### ISSUE THREAD

**Issue by Quillraven** [xpenatan/gdx-teavm#107]
I am wondering if this is a TeaVM issue or in general a mobile browser issue. My game is working totally fine on desktop browsers but on mobile it has issues with audio. 
To me it feels like "concurrent" audio playback isn't working because it simply turns off the music, when a sound effect is played.

Any ideas how that can be solved?

Link to the project: https://github.com/Quillraven/MysticGarden
Link to the game: https://quillraven.github.io/MysticGarden/

**Comment by xpenatan** [comment]
Yes, there is a issue with sound. It's in my TODO list to update it and have the same implementation as GWT.  Some people in discord replaced sourcec code with old sound code from teavm repository. 
https://github.com/konsoletyper/teavm-libgdx/blob/master/core/src/main/java/org/teavm/libgdx/TeaVMSound.java
https://github.com/konsoletyper/teavm-libgdx/blob/master/core/src/main/java/org/teavm/libgdx/TeaVMMusic.java

**Comment by Quillraven** [comment]
Ok, thanks for the update! Good to hear that this is already known and will be worked on in the future 👍
