### ISSUE TITLE
Problem with Version 1.0.2

### ISSUE THREAD

**Issue by Quillraven** [xpenatan/gdx-teavm#128]
Hi,

you mentioned that we should create issues here if we face issues with version 1.0.0+.

You can find the project [here](https://github.com/Quillraven/Masamune). When I update the gdxTeaVMVersion in `gradle.properties` from 1.0.0-b9 to 1.0.2 then the page in the browser does not respond anymore and does not load anything it seems.

1.0.0-b9 is working just fine for me.

Also, the update requires a small adjustment in `TeaVMBuilder` class since `assetsPath.add` requires a FileHandle or something instead of a normal File. You will need to change that single line as well when updating to 1.0.2.

Let me know if you need additional information :)

**Comment by xpenatan** [comment]
Fixed in 1.0.3  https://github.com/xpenatan/gdx-teavm/commit/082ac2a0a5dfe4b554725b3c87f2ade0a9b81fd4.

**Comment by Quillraven** [comment]
works, thanks a lot!
