### ISSUE TITLE
AudioContext issue: Music play causes 'Cannot read properties of undefined reading "0"'

### ISSUE THREAD

**Issue by Quillraven** [xpenatan/gdx-teavm#133]
Hi,

I have an issue which I think is related to playing music. The game crashes (see screenshots below). However, I am not sure why this happens or how to solve it. Can you please help?

I have a LoadingScreen which does not play any audio at all. It is responsible for loading all the assets including music/sound. After that, the user is required to click to continue to the main menu.

In the main menu I play a music file which causes the problem. I read in google that in web development someone should call "getAudioContext().resume()" to fix that problem but how would I do that?

If it helps, here is the link to the project I am trying to run in TeaVM. The branch is "update2024" and not master: https://github.com/Quillraven/Quilly-s-Adventure/tree/update2024

![image](https://github.com/user-attachments/assets/c2b6fd4f-8332-4fd9-b702-05c86f93d9e6)
![image](https://github.com/user-attachments/assets/89e0392a-9504-42c4-96fd-36898af79d45)

**Comment by xpenatan** [comment]
Hi @Quillraven. Snapshot contains the fix. For some reason this error was not happening using MusicTest so I didnt catch it before. 

There is still issues with pool objections using reflectionpool. Its better to to setup all pools manually instead of using ReflectionPool to get away of refleciton headaches

**Comment by Quillraven** [comment]
Thank you, that solved the audio issue for me! Now I need to continue to fix some other reflection stuff I think. I know why I don't like reflection and try to avoid it nowadays :D
