### ISSUE TITLE
Mobile (Android) canvas position wrong

### ISSUE THREAD

**Issue by xpenatan** [xpenatan/gdx-teavm#87]
When doing some random testing I saw that the rendering space is shifted down.

![Screenshot_20230220-231711.png](https://user-images.githubusercontent.com/6472084/220231017-fc212701-dbd4-4225-b569-f89fe4df5ccf.png)

**Comment by noblemaster** [comment]
Indeed, I didn't notice it. It's probably the `index.html` which has additional stuff and interprets it as a line break. I'll have a look and fix...
