### ISSUE TITLE
ConcurrentHashMap issue

### ISSUE THREAD

**Issue by 4lfg24** [xpenatan/gdx-teavm#93]
Hi it's me again 😅 I was using the b-4 version of gdxTeaVM but i got this error during compilation: `| ERROR[0]
| Class: de/eskalon/commons/screen/ScreenManager.java:114
| Method: de.eskalon.commons.screen.ScreenManager.<init>()V
| Text: Class java.util.concurrent.ConcurrentHashMap was not found`
Is this specifically related to ScreenManager or ConcurrentHashMaps in general?

**Comment by xpenatan** [comment]
teavm don't have ConcurrentHashmap

There is a PR open but is not yet merged https://github.com/konsoletyper/teavm/pull/462

**Comment by 4lfg24** [comment]
I understand, thank you again for the help and your great work @xpenatan!
